# Generated by Django 4.1 on 2022-09-09 11:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(choices=[('HR', 'HUMAN RESOURCE'), ('ENGG', 'ENGINEERING'), ('ACC', 'ACCOUNTS'), ('MAN', 'MANAGEMENT')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_desp', models.TextField(max_length=400)),
                ('in_progress', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('documents', models.FileField(upload_to='media', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.department')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.role')),
                ('username', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
