# Generated by Django 4.1 on 2022-09-09 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0002_employee_email_alter_employee_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_package', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.salary'),
        ),
    ]
