# Generated by Django 4.1 on 2022-09-09 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0004_employee_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='username',
        ),
    ]
