# Generated by Django 4.1 on 2022-09-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0005_remove_employee_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='employeeprofile.salary'),
        ),
    ]
