# Generated by Django 4.1 on 2022-09-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0006_alter_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employeeprofile.tasks'),
        ),
    ]
