# Generated by Django 4.1 on 2022-09-11 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0007_employee_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='in_progress',
            new_name='is_done',
        ),
    ]
