# Generated by Django 4.1 on 2022-09-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0008_rename_in_progress_tasks_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_assigned',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.employee'),
        ),
    ]
