# Generated by Django 4.1 on 2022-09-12 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employeeprofile', '0010_delete_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_desp', models.TextField(max_length=400)),
                ('is_done', models.BooleanField(default=False)),
                ('task_assigned', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='employeeprofile.employee')),
            ],
        ),
    ]
